A zelentsov branch
AZelentsov343/afina pull request #3
Opened 2020-03-12 17:14 UTC by AZelentsov343

2020-03-12 17:16 UTC, AZelentsov343 commented
Оставил shared ptr, так как у меня есть указатели на голову и хвост. Если в списке один объект, то они оба указывают на него.

2020-03-13 17:10 UTC, blumix requested changes

2020-03-13 17:10 UTC, blumix commented on src/storage/SimpleLRU.h
>          std::shared_ptr<lru_node> prev;
нужно всё-таки переделать на uniqe_ptr потому, что владение фактически уникальное.

2020-03-13 17:10 UTC, blumix commented on src/storage/SimpleLRU.cpp
> +    if (node_found.next != nullptr) { //moving recently used element to the tail
лучше вынести такие куски кода, как "сдвиинуть элемент в начало" и "удалить элемент" в отдельные функции.

2020-03-13 20:17 UTC, AZelentsov343 commented
Переделал на unique_ptr и перенес повторяющиеся конструкции в отдельные функции

2020-03-20 15:48 UTC, blumix requested changes

2020-03-20 15:48 UTC, blumix commented on src/storage/SimpleLRU.cpp
> +        bool SimpleLRU::Put(const std::string &key, const std::string &value) {
Всё-таки нужно использовать clang-format для того, что бы весь код был единообразным.

2020-03-20 15:48 UTC, blumix commented on src/storage/SimpleLRU.cpp
> +        bool SimpleLRU::Put(const std::string &key, const std::string &value) {
И делать один PR на одну домашку. Иначе проверять становится очень тяжело.

2020-03-20 15:48 UTC, blumix commented on src/storage/SimpleLRU.cpp
> +            node_found.value = value;
ты выставил значение, но так и не обновил _cur_size

2020-03-20 15:48 UTC, blumix commented on src/storage/SimpleLRU.cpp
> +                return Set(key, value);
Плохо, что ты делаешь find () дважды, за одну операцию. Этого можно избежать

2020-03-26 22:01 UTC, AZelentsov343 commented
исправил ошибки и сделал отдельный PR для 2ой домашки

2020-03-26 22:01 UTC, AZelentsov343 commented on src/storage/SimpleLRU.cpp
> +                return Set(key, value);
исправил ошибки и сделал отдельный PR для 2ой домашки

2020-03-28 21:03 UTC, merged